---
version: "2"

services:
    #  opentsdb:
    #    container_name: opentsdb
    #    image: petergrace/opentsdb-docker
    #    environment:
    #     - TSD_CONF_tsd__core__auto_create_metrics=True
    #     - TSD_CONF_tsd__network__port=4242
    #    ports:
    #     - 4242:4242
    #     - 2181:2181
  opentsdb:
    container_name: opentsdb
    build: docker/opentsdb
    image: t0mmyt/opentsdb
    environment:
     - TSD_CONF_tsd__core__auto_create_metrics=True
     - TSD_CONF_tsd__network__port=4242
    ports:
     - 4242:4242
     - 2181:2181
  observation:
    container_name: observation
    build: docker/obs
    image: t0mmyt/obs
    environment:
      # - OPENTSDB=172.16.1.90
      - OPENTSDB=opentsdb
      - OBSAPI_LISTEN_PORT=8010
    volumes:
      - ./code:/opt/code
    ports:
      - 8001:8001
  tsdatastore:
    container_name: tsdatastore
    build: docker/tsdatastore
    image: t0mmyt/tsdatastore
    environment:
#      - OPENTSDB=172.16.1.90
      - OPENTSDB=opentsdb
      - TSDBAPI_LISTEN_PORT=8010
    volumes:
      - ./code:/opt/code
    ports:
      - 8010:8010
  render:
    container_name: render
    build: docker/render
    image: t0mmyt/render
    environment:
      - TSDBAPI_HOST=tsdatastore
      - TSDBAPI_PORT=8010
    volumes:
      - ./code:/opt/code
    ports:
      - 8002:8002
  interface:
    container_name: interface
    build: docker/interface
    image: t0mmyt/interface
    environment:
      - RENDER=render:8002
      - OBSERVATION=observation:8001
      - TSDBAPI=tsdatastore:8010
    volumes:
      - ./code:/opt/code
    ports:
      - 8000:8000
